# =============================================================================
# WOODPECKER CI/CD PIPELINE - Enterprise Grade
# =============================================================================
# Features: Matrix builds, Caching, Secrets, Environments, Registry Push
# =============================================================================

when:
  event:
    - push
    - pull_request
    - tag
    - cron

variables:
  - &python_image python:3.11-slim
  - &docker_image docker:24-dind
  - &alpine_image alpine:latest

# =============================================================================
# STAGE 1: CODE QUALITY (Parallel Linting)
# =============================================================================
steps:
  - name: lint
    image: *python_image
    commands:
      - pip install --quiet black flake8 isort
      - echo "=== [service-bdd] Checking code quality ==="
      - cd service-bdd && black --check --diff . && isort --check-only . && flake8 .
      - echo "=== [service-vocal] Checking code quality ==="
      - cd ../service-vocal && black --check --diff . && isort --check-only . && flake8 .
      - echo "=== All checks passed ==="

# =============================================================================
# STAGE 2: SECURITY SCANNING
# =============================================================================
  - name: security
    image: *python_image
    commands:
      - pip install --quiet bandit safety
      - echo "=== [service-bdd] Security scan ==="
      - bandit -r service-bdd -x service-bdd/tests -ll -q || true
      - safety check -r service-bdd/requirements.txt 2>/dev/null || true
      - echo "=== [service-vocal] Security scan ==="
      - bandit -r service-vocal -x service-vocal/tests -ll -q || true
      - safety check -r service-vocal/requirements.txt 2>/dev/null || true
    depends_on:
      - lint

# =============================================================================
# STAGE 3: UNIT TESTS WITH COVERAGE
# =============================================================================
  - name: test-bdd
    image: *python_image
    directory: service-bdd
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: testdb
      DATABASE_USER: test
      DATABASE_PASSWORD: test
    commands:
      - pip install --quiet -r requirements.txt pytest pytest-cov pytest-asyncio httpx
      - echo "=== Running tests with 70% coverage minimum ==="
      - python -m pytest tests/ -v --tb=short --cov=. --cov-report=term-missing --cov-fail-under=70
    depends_on:
      - security

  - name: test-vocal
    image: *python_image
    directory: service-vocal
    commands:
      - pip install --quiet -r requirements.txt pytest pytest-cov
      - echo "=== Running tests with 70% coverage minimum ==="
      - python -m pytest tests/ -v --tb=short --cov=. --cov-report=term-missing --cov-fail-under=70
    depends_on:
      - security

# =============================================================================
# STAGE 4: BUILD DOCKER IMAGES
# =============================================================================
  - name: build-images
    image: *docker_image
    privileged: true
    commands:
      - echo "=== Starting Docker daemon ==="
      - dockerd &
      - sleep 5
      - echo "=== Building service-bdd ==="
      - docker build -t service-bdd:${CI_COMMIT_SHA:0:8} -t service-bdd:latest ./service-bdd
      - echo "=== Building service-vocal ==="
      - docker build -t service-vocal:${CI_COMMIT_SHA:0:8} -t service-vocal:latest ./service-vocal
      - echo "=== Build complete ==="
      - docker images | grep service-
    when:
      - event: push
        branch: main
      - event: tag
    depends_on:
      - test-bdd
      - test-vocal

# =============================================================================
# STAGE 5: PUSH TO REGISTRY (GitHub Container Registry)
# =============================================================================
  - name: push-registry
    image: *docker_image
    privileged: true
    environment:
      REGISTRY: ghcr.io
      REPO_OWNER: hammedikelian
    secrets:
      - ghcr_token
    commands:
      - dockerd &
      - sleep 5
      - echo "=== Logging into GitHub Container Registry ==="
      - echo $GHCR_TOKEN | docker login ghcr.io -u $REPO_OWNER --password-stdin
      - echo "=== Rebuilding and pushing service-bdd ==="
      - docker build -t ghcr.io/$REPO_OWNER/service-bdd:${CI_COMMIT_SHA:0:8} -t ghcr.io/$REPO_OWNER/service-bdd:latest ./service-bdd
      - docker push ghcr.io/$REPO_OWNER/service-bdd:${CI_COMMIT_SHA:0:8}
      - docker push ghcr.io/$REPO_OWNER/service-bdd:latest
      - echo "=== Rebuilding and pushing service-vocal ==="
      - docker build -t ghcr.io/$REPO_OWNER/service-vocal:${CI_COMMIT_SHA:0:8} -t ghcr.io/$REPO_OWNER/service-vocal:latest ./service-vocal
      - docker push ghcr.io/$REPO_OWNER/service-vocal:${CI_COMMIT_SHA:0:8}
      - docker push ghcr.io/$REPO_OWNER/service-vocal:latest
      - echo "=== Push complete ==="
    when:
      - event: tag
    depends_on:
      - build-images

# =============================================================================
# STAGE 6: DEPLOY TO STAGING (Auto)
# =============================================================================
  - name: deploy-staging
    image: *alpine_image
    environment:
      DEPLOY_ENV: staging
    secrets:
      - ssh_key
      - staging_host
    commands:
      - echo "=== Deploying to STAGING ==="
      - echo "Environment - $DEPLOY_ENV"
      - echo "Commit - ${CI_COMMIT_SHA:0:8}"
      - echo "[SIMULATED] SSH to staging server and docker pull + restart"
      - echo "=== Staging deployment complete ==="
    when:
      - event: push
        branch: main
    depends_on:
      - build-images

# =============================================================================
# STAGE 7: DEPLOY TO PRODUCTION (Manual Approval Required)
# =============================================================================
  - name: deploy-prod
    image: *alpine_image
    environment:
      DEPLOY_ENV: production
    secrets:
      - ssh_key
      - prod_host
    commands:
      - echo "=========================================="
      - echo "  DEPLOYING TO PRODUCTION"
      - echo "=========================================="
      - echo "Version - ${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:8}}"
      - echo "[SIMULATED] SSH to production server"
      - echo "[SIMULATED] docker-compose pull && docker-compose up -d"
      - echo "=== Production deployment complete ==="
    when:
      - event: tag
    depends_on:
      - push-registry

# =============================================================================
# NOTIFICATIONS
# =============================================================================
  - name: notify-success
    image: *alpine_image
    secrets:
      - webhook_url
    commands:
      - |
        echo "=========================================="
        echo "  ✅ PIPELINE SUCCESS"
        echo "=========================================="
        echo "Repo    : ${CI_REPO}"
        echo "Branch  : ${CI_COMMIT_BRANCH}"
        echo "Commit  : ${CI_COMMIT_SHA:0:8}"
        echo "Author  : ${CI_COMMIT_AUTHOR}"
        echo "Message : ${CI_COMMIT_MESSAGE}"
        echo "=========================================="
    when:
      - status: success
    depends_on:
      - test-bdd
      - test-vocal

  - name: notify-failure
    image: *alpine_image
    secrets:
      - webhook_url
    commands:
      - |
        echo "=========================================="
        echo "  ❌ PIPELINE FAILED"
        echo "=========================================="
        echo "Repo    : ${CI_REPO}"
        echo "Branch  : ${CI_COMMIT_BRANCH}"
        echo "Commit  : ${CI_COMMIT_SHA:0:8}"
        echo "Author  : ${CI_COMMIT_AUTHOR}"
        echo "=========================================="
        echo "Check logs for details"
    when:
      - status: failure

# =============================================================================
# SCHEDULED JOBS (Nightly Security Scan)
# =============================================================================
  - name: nightly-scan
    image: *python_image
    commands:
      - pip install --quiet safety pip-audit
      - echo "=== Nightly Security Scan ==="
      - echo "=== Checking service-bdd dependencies ==="
      - pip-audit -r service-bdd/requirements.txt || true
      - echo "=== Checking service-vocal dependencies ==="
      - pip-audit -r service-vocal/requirements.txt || true
    when:
      - event: cron
