when:
  event: [push, pull_request, tag]
  branch: [main, develop]

steps:
  - name: info
    image: alpine:latest
    commands:
      - echo "Branch:" $CI_COMMIT_BRANCH
      - echo "Commit:" $CI_COMMIT_SHA
      - echo "Event:" $CI_PIPELINE_EVENT

  - name: test-service-bdd
    image: python:3.11-slim
    directory: service-bdd
    commands:
      - pip install -r requirements.txt
      - python -c "import app; print('Import service-bdd OK')"

  - name: test-service-vocal
    image: python:3.11-slim
    directory: service-vocal
    commands:
      - pip install -r requirements.txt
      - python -c "import app; print('Import service-vocal OK')"

  - name: notify-success
    image: alpine:latest
    commands:
      - echo "Pipeline termine avec succes!"
    when:
      - status: success
