when:
  event:
    - push
    - pull_request
    - tag
  branch:
    - main
    - develop

steps:
  - name: info
    image: alpine:latest
    commands:
      - echo "=== Pipeline Info ==="
      - echo "Branch = $CI_COMMIT_BRANCH"
      - echo "Commit = $CI_COMMIT_SHA"
      - echo "Event = $CI_PIPELINE_EVENT"

  - name: test-service-bdd
    image: python:3.11-slim
    directory: service-bdd
    commands:
      - pip install --quiet -r requirements.txt
      - python test_imports.py

  - name: test-service-vocal
    image: python:3.11-slim
    directory: service-vocal
    commands:
      - pip install --quiet -r requirements.txt
      - python test_imports.py

  - name: success
    image: alpine:latest
    commands:
      - echo "=== Pipeline Success ==="
